/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fast_flyer_com_jnidemo_JNItest */

#ifndef _Included_fast_flyer_com_jnidemo_JNItest
#define _Included_fast_flyer_com_jnidemo_JNItest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fast_flyer_com_jnidemo_JNItest
 * Method:    getStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fast_flyer_com_jnidemo_JNItest_getStrFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
